// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwisbUdtx0iCaVWgG-bcId8x0zKWwihAg',
    appId: '1:867866688012:web:2e4286edbdea2dacbacc29',
    messagingSenderId: '867866688012',
    projectId: 'marketplaceapp-529e0',
    authDomain: 'marketplaceapp-529e0.firebaseapp.com',
    storageBucket: 'marketplaceapp-529e0.firebasestorage.app',
    measurementId: 'G-601NDVBM2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4zuDMj01FbUnh_5WWdMfQ6uRbv3QlhQA',
    appId: '1:867866688012:android:94980c342ad33a9dbacc29',
    messagingSenderId: '867866688012',
    projectId: 'marketplaceapp-529e0',
    storageBucket: 'marketplaceapp-529e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrxxJBZxU-M8IhLQwSdWKa6zymXrmKqhg',
    appId: '1:867866688012:ios:bfd618254b2a792dbacc29',
    messagingSenderId: '867866688012',
    projectId: 'marketplaceapp-529e0',
    storageBucket: 'marketplaceapp-529e0.firebasestorage.app',
    iosBundleId: 'com.example.marketplaceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrxxJBZxU-M8IhLQwSdWKa6zymXrmKqhg',
    appId: '1:867866688012:ios:bfd618254b2a792dbacc29',
    messagingSenderId: '867866688012',
    projectId: 'marketplaceapp-529e0',
    storageBucket: 'marketplaceapp-529e0.firebasestorage.app',
    iosBundleId: 'com.example.marketplaceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwisbUdtx0iCaVWgG-bcId8x0zKWwihAg',
    appId: '1:867866688012:web:4381d9899bae5f7abacc29',
    messagingSenderId: '867866688012',
    projectId: 'marketplaceapp-529e0',
    authDomain: 'marketplaceapp-529e0.firebaseapp.com',
    storageBucket: 'marketplaceapp-529e0.firebasestorage.app',
    measurementId: 'G-RVCQVCD7GQ',
  );
}
